# DO NOT TOUCH THIS FILE!

# Description: Funding for the Bot thru Github Sponsors.

github: [MeAlam1] # All Authors will be added here.
patreon: htoad
open_collective: # Replace with a single Open Collective username
ko_fi: htoad
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']